################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
pkg/f2833x/v140/DSP2833x_common/source/DSP2833x_ADC_cal.obj: ../pkg/f2833x/v140/DSP2833x_common/source/DSP2833x_ADC_cal.asm $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"c:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.4/bin/cl2000" -v28 -ml -mt --float_support=softlib --include_path="c:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.4/include" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/idle" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/f2833x/v140/DSP2833x_headers/include" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/f2833x/v140/DSP2833x_common/include" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/comm" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/conin" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/conout" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/scon" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/zcon" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/os" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3" --advice:performance=all -g --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="pkg/f2833x/v140/DSP2833x_common/source/DSP2833x_ADC_cal.pp" --obj_directory="pkg/f2833x/v140/DSP2833x_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

pkg/f2833x/v140/DSP2833x_common/source/DSP2833x_Adc.obj: ../pkg/f2833x/v140/DSP2833x_common/source/DSP2833x_Adc.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"c:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.4/bin/cl2000" -v28 -ml -mt --float_support=softlib --include_path="c:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.4/include" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/idle" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/f2833x/v140/DSP2833x_headers/include" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/f2833x/v140/DSP2833x_common/include" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/comm" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/conin" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/conout" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/scon" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/zcon" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/os" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3" --advice:performance=all -g --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="pkg/f2833x/v140/DSP2833x_common/source/DSP2833x_Adc.pp" --obj_directory="pkg/f2833x/v140/DSP2833x_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

pkg/f2833x/v140/DSP2833x_common/source/DSP2833x_CpuTimers.obj: ../pkg/f2833x/v140/DSP2833x_common/source/DSP2833x_CpuTimers.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"c:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.4/bin/cl2000" -v28 -ml -mt --float_support=softlib --include_path="c:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.4/include" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/idle" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/f2833x/v140/DSP2833x_headers/include" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/f2833x/v140/DSP2833x_common/include" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/comm" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/conin" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/conout" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/scon" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/zcon" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/os" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3" --advice:performance=all -g --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="pkg/f2833x/v140/DSP2833x_common/source/DSP2833x_CpuTimers.pp" --obj_directory="pkg/f2833x/v140/DSP2833x_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

pkg/f2833x/v140/DSP2833x_common/source/DSP2833x_DefaultIsr.obj: ../pkg/f2833x/v140/DSP2833x_common/source/DSP2833x_DefaultIsr.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"c:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.4/bin/cl2000" -v28 -ml -mt --float_support=softlib --include_path="c:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.4/include" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/idle" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/f2833x/v140/DSP2833x_headers/include" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/f2833x/v140/DSP2833x_common/include" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/comm" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/conin" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/conout" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/scon" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/zcon" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/os" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3" --advice:performance=all -g --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="pkg/f2833x/v140/DSP2833x_common/source/DSP2833x_DefaultIsr.pp" --obj_directory="pkg/f2833x/v140/DSP2833x_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

pkg/f2833x/v140/DSP2833x_common/source/DSP2833x_EQep.obj: ../pkg/f2833x/v140/DSP2833x_common/source/DSP2833x_EQep.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"c:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.4/bin/cl2000" -v28 -ml -mt --float_support=softlib --include_path="c:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.4/include" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/idle" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/f2833x/v140/DSP2833x_headers/include" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/f2833x/v140/DSP2833x_common/include" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/comm" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/conin" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/conout" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/scon" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/zcon" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/os" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3" --advice:performance=all -g --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="pkg/f2833x/v140/DSP2833x_common/source/DSP2833x_EQep.pp" --obj_directory="pkg/f2833x/v140/DSP2833x_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

pkg/f2833x/v140/DSP2833x_common/source/DSP2833x_Gpio.obj: ../pkg/f2833x/v140/DSP2833x_common/source/DSP2833x_Gpio.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"c:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.4/bin/cl2000" -v28 -ml -mt --float_support=softlib --include_path="c:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.4/include" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/idle" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/f2833x/v140/DSP2833x_headers/include" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/f2833x/v140/DSP2833x_common/include" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/comm" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/conin" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/conout" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/scon" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/zcon" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/os" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3" --advice:performance=all -g --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="pkg/f2833x/v140/DSP2833x_common/source/DSP2833x_Gpio.pp" --obj_directory="pkg/f2833x/v140/DSP2833x_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

pkg/f2833x/v140/DSP2833x_common/source/DSP2833x_PieCtrl.obj: ../pkg/f2833x/v140/DSP2833x_common/source/DSP2833x_PieCtrl.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"c:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.4/bin/cl2000" -v28 -ml -mt --float_support=softlib --include_path="c:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.4/include" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/idle" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/f2833x/v140/DSP2833x_headers/include" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/f2833x/v140/DSP2833x_common/include" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/comm" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/conin" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/conout" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/scon" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/zcon" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/os" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3" --advice:performance=all -g --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="pkg/f2833x/v140/DSP2833x_common/source/DSP2833x_PieCtrl.pp" --obj_directory="pkg/f2833x/v140/DSP2833x_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

pkg/f2833x/v140/DSP2833x_common/source/DSP2833x_PieVect.obj: ../pkg/f2833x/v140/DSP2833x_common/source/DSP2833x_PieVect.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"c:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.4/bin/cl2000" -v28 -ml -mt --float_support=softlib --include_path="c:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.4/include" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/idle" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/f2833x/v140/DSP2833x_headers/include" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/f2833x/v140/DSP2833x_common/include" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/comm" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/conin" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/conout" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/scon" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/zcon" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/os" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3" --advice:performance=all -g --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="pkg/f2833x/v140/DSP2833x_common/source/DSP2833x_PieVect.pp" --obj_directory="pkg/f2833x/v140/DSP2833x_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

pkg/f2833x/v140/DSP2833x_common/source/DSP2833x_Sci.obj: ../pkg/f2833x/v140/DSP2833x_common/source/DSP2833x_Sci.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"c:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.4/bin/cl2000" -v28 -ml -mt --float_support=softlib --include_path="c:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.4/include" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/idle" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/f2833x/v140/DSP2833x_headers/include" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/f2833x/v140/DSP2833x_common/include" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/comm" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/conin" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/conout" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/scon" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/zcon" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/os" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3" --advice:performance=all -g --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="pkg/f2833x/v140/DSP2833x_common/source/DSP2833x_Sci.pp" --obj_directory="pkg/f2833x/v140/DSP2833x_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

pkg/f2833x/v140/DSP2833x_common/source/DSP2833x_SysCtrl.obj: ../pkg/f2833x/v140/DSP2833x_common/source/DSP2833x_SysCtrl.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"c:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.4/bin/cl2000" -v28 -ml -mt --float_support=softlib --include_path="c:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.4/include" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/idle" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/f2833x/v140/DSP2833x_headers/include" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/f2833x/v140/DSP2833x_common/include" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/comm" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/conin" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/conout" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/scon" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/zcon" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/os" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3" --advice:performance=all -g --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="pkg/f2833x/v140/DSP2833x_common/source/DSP2833x_SysCtrl.pp" --obj_directory="pkg/f2833x/v140/DSP2833x_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

pkg/f2833x/v140/DSP2833x_common/source/DSP2833x_usDelay.obj: ../pkg/f2833x/v140/DSP2833x_common/source/DSP2833x_usDelay.asm $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"c:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.4/bin/cl2000" -v28 -ml -mt --float_support=softlib --include_path="c:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.4/include" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/idle" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/f2833x/v140/DSP2833x_headers/include" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/f2833x/v140/DSP2833x_common/include" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/comm" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/conin" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/conout" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/scon" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/zcon" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3/pkg/os" --include_path="C:/Users/JALILFRANCISCO/Documents/Maestria/5_semestre/MSEControllerV5.3" --advice:performance=all -g --diag_warning=225 --display_error_number --diag_wrap=off --preproc_with_compile --preproc_dependency="pkg/f2833x/v140/DSP2833x_common/source/DSP2833x_usDelay.pp" --obj_directory="pkg/f2833x/v140/DSP2833x_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


